#
# Makefile for the show hardware info drivers.
#
##include $(srctree)/drivers/misc/mediatek/Makefile.custom

#obj-$(CONFIG_PRIZE_HARDWARE_INFO) +=  hardware_info.o
obj-y +=  lcd_bias.o
obj-$(CONFIG_PRIZE_TPS65132_SUPPORT) +=  tps65132.o