extern int display_bias_enable(void);
extern int display_bias_enable_v(unsigned int);
extern int display_bias_disable(void);
extern int display_bias_vpos_enable(int enable);
extern int display_bias_vneg_enable(int enable);
extern int display_bias_vpos_set(int mv);
extern int display_bias_vneg_set(int mv);
extern int display_ldo18_enable(int enable);
extern int display_ldo28_enable(int enable);
extern int display_fd_enable(int enable);