#ccflags-y += -I$(srctree)/drivers/misc/mediatek/leds/$(MTK_PLATFORM)
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/video/include
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/imgsensor/inc/
obj-y	+= prize_dual_camera_als.o
obj-y	+= prize_stk3x3x.o