ccflags-y += -I$(srctree)/drivers/spi/mediatek/$(MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/spi/mediatek/$(MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/input/fingerprint/icnf7xxx_tee

# For beanpod v2.5.1 version.Maybe this path is not correct. you have to ensure this path in project.
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/teei/V1.0/tz_vfs/

# For beanpod v2.8.0 version.Maybe this path is not correct. you have to ensure this path in project.
ccflags-y += -I$(srctree)/drivers/misc/mediatek/teei/280/tz_driver/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/teei/280/common/include

obj-y += fpsensor_spi_tee.o

