#
# Makefile for the show hardware info drivers.
#
##include $(srctree)/drivers/misc/mediatek/Makefile.custom

#obj-$(CONFIG_PRIZE_HARDWARE_INFO) +=  hardware_info.o
obj-$(CONFIG_PRIZE_HARDWARE_INFO) +=  hardware_info.o
obj-$(CONFIG_MEDIATEK_MT6577_AUXADC) += lcm_auxadc.o
obj-$(CONFIG_SC27XX_ADC) += lcm_auxadc.o