# Makefile for the focaltech touchscreen drivers.


obj-y	+=  focaltech_core.o
obj-y	+= focaltech_ex_fun.o
obj-y	+=  focaltech_ex_mode.o
obj-y	+=  focaltech_gesture.o
obj-y	+=  focaltech_esdcheck.o
obj-y	+=  focaltech_point_report_check.o



obj-y	+=  focaltech_flash.o



obj-y	+=  focaltech_spi.o
obj-y	+=  rawdata_differ.o
